export const SUPABASE_URL_ENV_KEYS = ['SUPABASE_URL', 'NUXT_SUPABASE_URL'] as const;
export const SUPABASE_SECRET_KEY_ENV_KEYS = [
  'SUPABASE_SECRET_KEY',
  'NUXT_SUPABASE_SECRET_KEY',
  'SUPABASE_ANON_KEY',
  'NUXT_SUPABASE_ANON_KEY',
] as const;

export const SUPABASE_AUTHORIZATION_HEADER_PREFIX = 'Bearer ';
