services:
  blog-api:
    image: ghcr.io/TON_USER/blog-api:prod
    container_name: blog-api
    restart: unless-stopped
    env_file:
      - ../env/blog-api.prod.env
    networks:
      - magify-network

  blog-web:
    image: ghcr.io/TON_USER/blog-web:prod
    container_name: blog-web
    restart: unless-stopped
    env_file:
      - ../env/blog-web.prod.env
    networks:
      - magify-network

  prospection-api:
    image: ghcr.io/TON_USER/prospection-api:prod
    container_name: prospection-api
    restart: unless-stopped
    env_file:
      - ../env/prospection-api.prod.env
    networks:
      - magify-network

  prospection-web:
    image: ghcr.io/TON_USER/prospection-web:prod
    container_name: prospection-web
    restart: unless-stopped
    env_file:
      - ../env/prospection-web.prod.env
    networks:
      - magify-network

  social-api:
    image: ghcr.io/TON_USER/social-api:prod
    container_name: social-api
    restart: unless-stopped
    env_file:
      - ../env/social-api.prod.env
    networks:
      - magify-network

  social-web:
    image: ghcr.io/TON_USER/social-web:prod
    container_name: social-web
    restart: unless-stopped
    env_file:
      - ../env/social-web.prod.env
    networks:
      - magify-network

networks:
  magify-network:
    external: true
