services:
  blog-api:
    image: ghcr.io/brunstad/blog-api:prod
    container_name: blog-api
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      APP_NAME: blog
      PORT: 30000
      POSTGRES_DB: ${BLOG_POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_APP_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_APP_USER}
      DATABASE_URL: "postgresql://${POSTGRES_APP_USER}:${POSTGRES_APP_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${BLOG_POSTGRES_DB}"
    networks:
      - magify-network

  blog-web:
    image: ghcr.io/brunstad/blog-web:prod
    container_name: blog-web
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      APP_URL: http://blog.magify.local
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 30000
      NUXT_PUBLIC_API_URL: http://blog-api.magify.local
    networks:
      - magify-network

  prospection-api:
    image: ghcr.io/brunstad/prospection-api:prod
    container_name: prospection-api
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      APP_NAME: prospection
      PORT: 30000
      POSTGRES_DB: ${PROSPECTION_POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_APP_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_APP_USER}
      DATABASE_URL: "postgresql://${POSTGRES_APP_USER}:${POSTGRES_APP_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${PROSPECTION_POSTGRES_DB}"
    networks:
      - magify-network

  prospection-web:
    image: ghcr.io/brunstad/prospection-web:prod
    container_name: prospection-web
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      APP_URL: http://prospection.magify.local
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 30000
      NUXT_PUBLIC_API_URL: http://prospection-api.magify.local
    networks:
      - magify-network

  social-api:
    image: ghcr.io/brunstad/social-api:prod
    container_name: social-api
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      APP_NAME: social
      PORT: 30000
      POSTGRES_DB: ${SOCIAL_POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_APP_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_APP_USER}
      DATABASE_URL: "postgresql://${POSTGRES_APP_USER}:${POSTGRES_APP_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${SOCIAL_POSTGRES_DB}"
    networks:
      - magify-network

  social-web:
    image: ghcr.io/brunstad/social-web:prod
    container_name: social-web
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      APP_URL: http://social.magify.local
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 30000
      NUXT_PUBLIC_API_URL: http://social-api.magify.local
    networks:
      - magify-network

networks:
  magify-network:
    external: true
