import {
  BUSINESS_POSITIONING_KEYWORD_EXTRACTION_PROMPT_CONFIG_KEY,
  CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_PROMPT_CONFIG_KEY,
  DEFAULT_BUSINESS_POSITIONING_KEYWORD_EXTRACTION_AI_INPUT,
  DEFAULT_BUSINESS_POSITIONING_KEYWORD_EXTRACTION_AI_INSTRUCTIONS,
  DEFAULT_BUSINESS_POSITIONING_KEYWORD_EXTRACTION_AI_MODEL,
  DEFAULT_CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_AI_INPUT,
  DEFAULT_CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_AI_INSTRUCTIONS,
  DEFAULT_CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_AI_MODEL,
  DEFAULT_KEYWORD_ANALYSIS_AI_INPUT,
  DEFAULT_KEYWORD_ANALYSIS_AI_INSTRUCTIONS,
  DEFAULT_KEYWORD_ANALYSIS_AI_MODEL,
  DEFAULT_KEYWORD_ANALYSIS_MINI_SCAN_AI_INPUT,
  DEFAULT_KEYWORD_ANALYSIS_MINI_SCAN_AI_INSTRUCTIONS,
  DEFAULT_KEYWORD_ANALYSIS_MINI_SCAN_AI_MODEL,
  DEFAULT_KEYWORD_GROUPING_AI_INPUT,
  DEFAULT_KEYWORD_GROUPING_AI_INSTRUCTIONS,
  DEFAULT_KEYWORD_GROUPING_AI_MODEL,
  DEFAULT_KEYWORD_GROUP_TEMPLATE_AI_INPUT,
  DEFAULT_KEYWORD_GROUP_TEMPLATE_AI_INSTRUCTIONS,
  DEFAULT_KEYWORD_GROUP_TEMPLATE_AI_MODEL,
  DEFAULT_BLOG_ARTICLE_FROM_SUGGESTION_AI_INPUT,
  DEFAULT_BLOG_ARTICLE_FROM_SUGGESTION_AI_INSTRUCTIONS,
  DEFAULT_BLOG_ARTICLE_FROM_SUGGESTION_AI_MODEL,
  DEFAULT_BLOG_ARTICLE_PLAN_FROM_SUGGESTION_AI_INPUT,
  DEFAULT_BLOG_ARTICLE_PLAN_FROM_SUGGESTION_AI_INSTRUCTIONS,
  DEFAULT_BLOG_ARTICLE_PLAN_FROM_SUGGESTION_AI_MODEL,
  DEFAULT_BLOG_ARTICLE_SECONDARY_KEYWORDS_SUGGESTION_AI_INPUT,
  DEFAULT_BLOG_ARTICLE_SECONDARY_KEYWORDS_SUGGESTION_AI_INSTRUCTIONS,
  DEFAULT_BLOG_ARTICLE_SECONDARY_KEYWORDS_SUGGESTION_AI_MODEL,
  DEFAULT_KEYWORD_GROUP_DEDUPLICATION_AI_INPUT,
  DEFAULT_KEYWORD_GROUP_DEDUPLICATION_AI_INSTRUCTIONS,
  DEFAULT_KEYWORD_GROUP_DEDUPLICATION_AI_MODEL,
  DEFAULT_SEO_CLUSTER_SUGGESTION_AI_INPUT,
  DEFAULT_SEO_CLUSTER_SUGGESTION_AI_INSTRUCTIONS,
  DEFAULT_SEO_CLUSTER_SUGGESTION_AI_MODEL,
  BLOG_ARTICLE_FROM_SUGGESTION_PROMPT_CONFIG_KEY,
  KEYWORD_ANALYSIS_PROMPT_CONFIG_KEY,
  KEYWORD_ANALYSIS_MINI_SCAN_PROMPT_CONFIG_KEY,
  KEYWORD_GROUP_DEDUPLICATION_PROMPT_CONFIG_KEY,
  KEYWORD_GROUP_TEMPLATE_PROMPT_CONFIG_KEY,
  KEYWORD_GROUPING_PROMPT_CONFIG_KEY,
  BLOG_ARTICLE_SECONDARY_KEYWORDS_SUGGESTION_PROMPT_CONFIG_KEY,
  SEO_CLUSTER_SUGGESTION_PROMPT_CONFIG_KEY,
  LEGACY_KEYWORD_ANALYSIS_MINI_SCAN_AI_MODEL_SETTING_KEY,
  LEGACY_KEYWORD_ANALYSIS_MINI_SCAN_AI_PROMPT_SETTING_KEY,
  LEGACY_BUSINESS_POSITIONING_KEYWORD_EXTRACTION_AI_MODEL_SETTING_KEY,
  LEGACY_BUSINESS_POSITIONING_KEYWORD_EXTRACTION_AI_PROMPT_SETTING_KEY,
  LEGACY_CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_AI_MODEL_SETTING_KEY,
  LEGACY_CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_AI_PROMPT_SETTING_KEY,
  LEGACY_KEYWORD_ANALYSIS_AI_MODEL_SETTING_KEY,
  LEGACY_KEYWORD_ANALYSIS_AI_PROMPT_SETTING_KEY,
  LEGACY_KEYWORD_GROUPING_AI_MODEL_SETTING_KEY,
  LEGACY_KEYWORD_GROUPING_AI_PROMPT_SETTING_KEY,
  BLOG_ARTICLE_PLAN_FROM_SUGGESTION_PROMPT_CONFIG_KEY,
} from './settings.constants';

type PromptConfigDefaultEntry = {
  key: string;
  model: string;
  instructions: string;
  input: string;
  maxOutputTokens: number;
  legacyPromptKey?: string;
  legacyModelKey?: string;
};

export const PROMPT_CONFIG_DEFAULTS = {
  [KEYWORD_ANALYSIS_PROMPT_CONFIG_KEY]: {
    key: KEYWORD_ANALYSIS_PROMPT_CONFIG_KEY,
    model: DEFAULT_KEYWORD_ANALYSIS_AI_MODEL,
    instructions: DEFAULT_KEYWORD_ANALYSIS_AI_INSTRUCTIONS,
    input: DEFAULT_KEYWORD_ANALYSIS_AI_INPUT,
    maxOutputTokens: 1200,
    legacyPromptKey: LEGACY_KEYWORD_ANALYSIS_AI_PROMPT_SETTING_KEY,
    legacyModelKey: LEGACY_KEYWORD_ANALYSIS_AI_MODEL_SETTING_KEY,
  },
  [KEYWORD_ANALYSIS_MINI_SCAN_PROMPT_CONFIG_KEY]: {
    key: KEYWORD_ANALYSIS_MINI_SCAN_PROMPT_CONFIG_KEY,
    model: DEFAULT_KEYWORD_ANALYSIS_MINI_SCAN_AI_MODEL,
    instructions: DEFAULT_KEYWORD_ANALYSIS_MINI_SCAN_AI_INSTRUCTIONS,
    input: DEFAULT_KEYWORD_ANALYSIS_MINI_SCAN_AI_INPUT,
    maxOutputTokens: 200,
    legacyPromptKey: LEGACY_KEYWORD_ANALYSIS_MINI_SCAN_AI_PROMPT_SETTING_KEY,
    legacyModelKey: LEGACY_KEYWORD_ANALYSIS_MINI_SCAN_AI_MODEL_SETTING_KEY,
  },
  [CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_PROMPT_CONFIG_KEY]: {
    key: CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_PROMPT_CONFIG_KEY,
    model: DEFAULT_CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_AI_MODEL,
    instructions: DEFAULT_CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_AI_INSTRUCTIONS,
    input: DEFAULT_CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_AI_INPUT,
    maxOutputTokens: 800,
    legacyPromptKey:
      LEGACY_CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_AI_PROMPT_SETTING_KEY,
    legacyModelKey:
      LEGACY_CUSTOMER_PROBLEM_KEYWORD_EXTRACTION_AI_MODEL_SETTING_KEY,
  },
  [BUSINESS_POSITIONING_KEYWORD_EXTRACTION_PROMPT_CONFIG_KEY]: {
    key: BUSINESS_POSITIONING_KEYWORD_EXTRACTION_PROMPT_CONFIG_KEY,
    model: DEFAULT_BUSINESS_POSITIONING_KEYWORD_EXTRACTION_AI_MODEL,
    instructions: DEFAULT_BUSINESS_POSITIONING_KEYWORD_EXTRACTION_AI_INSTRUCTIONS,
    input: DEFAULT_BUSINESS_POSITIONING_KEYWORD_EXTRACTION_AI_INPUT,
    maxOutputTokens: 800,
    legacyPromptKey:
      LEGACY_BUSINESS_POSITIONING_KEYWORD_EXTRACTION_AI_PROMPT_SETTING_KEY,
    legacyModelKey:
      LEGACY_BUSINESS_POSITIONING_KEYWORD_EXTRACTION_AI_MODEL_SETTING_KEY,
  },
  [KEYWORD_GROUPING_PROMPT_CONFIG_KEY]: {
    key: KEYWORD_GROUPING_PROMPT_CONFIG_KEY,
    model: DEFAULT_KEYWORD_GROUPING_AI_MODEL,
    instructions: DEFAULT_KEYWORD_GROUPING_AI_INSTRUCTIONS,
    input: DEFAULT_KEYWORD_GROUPING_AI_INPUT,
    maxOutputTokens: 4000,
    legacyPromptKey: LEGACY_KEYWORD_GROUPING_AI_PROMPT_SETTING_KEY,
    legacyModelKey: LEGACY_KEYWORD_GROUPING_AI_MODEL_SETTING_KEY,
  },
  [KEYWORD_GROUP_TEMPLATE_PROMPT_CONFIG_KEY]: {
    key: KEYWORD_GROUP_TEMPLATE_PROMPT_CONFIG_KEY,
    model: DEFAULT_KEYWORD_GROUP_TEMPLATE_AI_MODEL,
    instructions: DEFAULT_KEYWORD_GROUP_TEMPLATE_AI_INSTRUCTIONS,
    input: DEFAULT_KEYWORD_GROUP_TEMPLATE_AI_INPUT,
    maxOutputTokens: 120,
  },
  [KEYWORD_GROUP_DEDUPLICATION_PROMPT_CONFIG_KEY]: {
    key: KEYWORD_GROUP_DEDUPLICATION_PROMPT_CONFIG_KEY,
    model: DEFAULT_KEYWORD_GROUP_DEDUPLICATION_AI_MODEL,
    instructions: DEFAULT_KEYWORD_GROUP_DEDUPLICATION_AI_INSTRUCTIONS,
    input: DEFAULT_KEYWORD_GROUP_DEDUPLICATION_AI_INPUT,
    maxOutputTokens: 1200,
  },
  [SEO_CLUSTER_SUGGESTION_PROMPT_CONFIG_KEY]: {
    key: SEO_CLUSTER_SUGGESTION_PROMPT_CONFIG_KEY,
    model: DEFAULT_SEO_CLUSTER_SUGGESTION_AI_MODEL,
    instructions: DEFAULT_SEO_CLUSTER_SUGGESTION_AI_INSTRUCTIONS,
    input: DEFAULT_SEO_CLUSTER_SUGGESTION_AI_INPUT,
    maxOutputTokens: 120,
  },
  [BLOG_ARTICLE_FROM_SUGGESTION_PROMPT_CONFIG_KEY]: {
    key: BLOG_ARTICLE_FROM_SUGGESTION_PROMPT_CONFIG_KEY,
    model: DEFAULT_BLOG_ARTICLE_FROM_SUGGESTION_AI_MODEL,
    instructions: DEFAULT_BLOG_ARTICLE_FROM_SUGGESTION_AI_INSTRUCTIONS,
    input: DEFAULT_BLOG_ARTICLE_FROM_SUGGESTION_AI_INPUT,
    maxOutputTokens: 2000,
  },
  [BLOG_ARTICLE_PLAN_FROM_SUGGESTION_PROMPT_CONFIG_KEY]: {
    key: BLOG_ARTICLE_PLAN_FROM_SUGGESTION_PROMPT_CONFIG_KEY,
    model: DEFAULT_BLOG_ARTICLE_PLAN_FROM_SUGGESTION_AI_MODEL,
    instructions: DEFAULT_BLOG_ARTICLE_PLAN_FROM_SUGGESTION_AI_INSTRUCTIONS,
    input: DEFAULT_BLOG_ARTICLE_PLAN_FROM_SUGGESTION_AI_INPUT,
    maxOutputTokens: 1200,
  },
  [BLOG_ARTICLE_SECONDARY_KEYWORDS_SUGGESTION_PROMPT_CONFIG_KEY]: {
    key: BLOG_ARTICLE_SECONDARY_KEYWORDS_SUGGESTION_PROMPT_CONFIG_KEY,
    model: DEFAULT_BLOG_ARTICLE_SECONDARY_KEYWORDS_SUGGESTION_AI_MODEL,
    instructions:
      DEFAULT_BLOG_ARTICLE_SECONDARY_KEYWORDS_SUGGESTION_AI_INSTRUCTIONS,
    input: DEFAULT_BLOG_ARTICLE_SECONDARY_KEYWORDS_SUGGESTION_AI_INPUT,
    maxOutputTokens: 900,
  },
} as const satisfies Record<string, PromptConfigDefaultEntry>;

export type PromptConfigKey = keyof typeof PROMPT_CONFIG_DEFAULTS;
