CREATE DATABASE admin OWNER admin;
CREATE DATABASE blog OWNER magify;
CREATE DATABASE prospection OWNER magify;
CREATE DATABASE social OWNER magify;

GRANT ALL PRIVILEGES ON DATABASE admin TO admin;
GRANT ALL PRIVILEGES ON DATABASE blog TO admin;
GRANT ALL PRIVILEGES ON DATABASE blog TO magify;
GRANT ALL PRIVILEGES ON DATABASE prospection TO admin;
GRANT ALL PRIVILEGES ON DATABASE prospection TO magify;
GRANT ALL PRIVILEGES ON DATABASE social TO admin;
GRANT ALL PRIVILEGES ON DATABASE social TO magify;
